# Example paths
# export ARDMK_DIR=/usr/share/arduino
# export ARDUINO_DIR=/home/lagunov/src/opensource/Arduino/build/linux/work
# export AVRDUDE_CONF=/home/lagunov/src/opensource/Arduino/build/linux/work/hardware/tools/avr/etc/avrdude.conf
# export AVR_TOOLS_DIR=/home/lagunov/src/opensource/Arduino/build/linux/work/hardware/tools/avr


ARDUINO_SKETCHBOOK := $(shell pwd)
BOARD_TAG := uno
ARDUINO_LIBS := DHT
include ../Arduino.mk
