# export ARDUINO_DIR := $(realpath ~/src/opensource/Arduino/build/linux/work)
# export ARDMK_DIR := /usr/share/arduino
# export AVR_TOOLS_DIR := $(realpath ~/src/opensource/Arduino/build/linux/work/hardware/arduino/avr)

BOARD_TAG = uno
include ../Arduino.mk
